/*******************************************************************************
 * Copyright (c) 2010 Red Hat, Inc.
 * Distributed under license by Red Hat, Inc. All rights reserved.
 * This program is made available under the terms of the
 * Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Red Hat, Inc. - initial API and implementation
 ******************************************************************************/
package de.unihannover.l3s.mws.bean;

import java.util.List;


import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.context.FacesContext;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ValueChangeEvent;
import javax.faces.event.ValueChangeListener;

import de.unihannover.l3s.mws.dao.TrackDao;
import de.unihannover.l3s.mws.model.Track;
import de.unihannover.l3s.mws.model.Utente;



@ManagedBean(name="tracks")
@SessionScoped
public class TrackBean {
	
	@ManagedProperty(value="#{user}")
	private User loggeduser;
	
	private Utente user;
	
	public void userChanged(ValueChangeEvent e){
		operation = e.getNewValue().toString();		
	}
	
	public void operationChanged(ValueChangeEvent e){
		userselected = e.getNewValue().toString();
		
	}
	
	
	@PostConstruct
    public void init() {

    }

// Anousheh
	List<Track> list;
	
	public String  operation ;
	List<Track> operationlist;

	public String  userselected ;
	List<Utente> userselectedList;
	
	public String getUserselected() {
		return userselected;
	}

	public void setUserselected(String userselected) {
		this.userselected = userselected;
	}

	public List<Utente> getUserselectedList() {
		TrackDao trackdao=new TrackDao(); 
		userselectedList=trackdao.getAllUsersInTrack();
		return userselectedList;
	}

	public void setUserselectedList(List<Utente> userselectedList) {
		this.userselectedList = userselectedList;
	}

	public List<Track> getList() {
		return list;
	}

	public void setList(List<Track> list) {
		this.list = list;
	}
	
	public Utente getUser() {
		return user;
	}

	public void setUser(Utente user) {
		this.user = user;
	}
	
	public User getLoggeduser() {
		return loggeduser;
	}

	public void setLoggeduser(User loggeduser) {
		this.loggeduser = loggeduser;
	}
	
	public void changeOperation(AjaxBehaviorEvent event){
		TrackDao trackdao=new TrackDao(); 
		List<Track> tracklist = trackdao.getTrackByOperationAndUser(this.operation,this.userselected);
		this.list=tracklist;
	}
	
	public void changeUserselected(AjaxBehaviorEvent event){
		TrackDao trackdao=new TrackDao(); 
		List<Track> tracklist = trackdao.getTrackByOperationAndUser(this.operation,this.userselected);
		this.list=tracklist;
	}
	
	
	//Anousheh 1
	public String loadList(){
		TrackDao trackdao=new TrackDao(); 
		List<Track> tracklist = trackdao.getAllTrackBeans();
		this.list=tracklist;
		return "trackchart";
	}
	
	 //Anousheh 2
	
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	//Generated by Object array
	  	public static class Operation{
	  		public String operationLabel;
	  		public String operationValue;
	  		
	  		public Operation(String operationLabel, String operationValue){
	  			this.operationLabel = operationLabel;
	  			this.operationValue = operationValue;
	  		}
	  		
	  		public String getOperationLabel(){
	  			return operationLabel;
	  		}
	  		
	  		public String getOperationValue(){
	  			return operationValue;
	  		}
	  	}
	  	
	  	public Operation[] operationList;
	  	
		public List<Track> getoperationList() {
			return list;
		}

		public void setoperationList(List<Track> operationlist) {
			this.operationlist = operationlist;
		}
		
	  	
	  	public Operation[] getOperationValue() {
	  		
	  		operationList = new Operation[6];
	  		operationList[0] = new Operation("Operation - Login", "Login");
	  		operationList[1] = new Operation("Operation - Search", "Search");
	  		operationList[2] = new Operation("Operation - SaveSearch", "Save Search");
	  		operationList[3] = new Operation("Operation - LoadSearchList", "Load Search List");
	  		operationList[4] = new Operation("Operation - SaveSiteSetting", "SaveSiteSetting");
	  		operationList[5] = new Operation("Operation - LoadStoryBoardList", "Load Story Board List");
	  		
	  		return operationList;
	  	
	  	}
}